// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	todos "first-task-alterra/internal/features/todos"

	mock "github.com/stretchr/testify/mock"
)

// Query is an autogenerated mock type for the Query type
type Query struct {
	mock.Mock
}

// AddTodo provides a mock function with given fields: newTodo
func (_m *Query) AddTodo(newTodo todos.Todo) error {
	ret := _m.Called(newTodo)

	if len(ret) == 0 {
		panic("no return value specified for AddTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(todos.Todo) error); ok {
		r0 = rf(newTodo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTodo provides a mock function with given fields: id
func (_m *Query) DeleteTodo(id uint) (todos.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 todos.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (todos.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) todos.Todo); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(todos.Todo)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTodo provides a mock function with given fields: owner
func (_m *Query) FindTodo(owner uint) ([]todos.Todo, error) {
	ret := _m.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for FindTodo")
	}

	var r0 []todos.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]todos.Todo, error)); ok {
		return rf(owner)
	}
	if rf, ok := ret.Get(0).(func(uint) []todos.Todo); ok {
		r0 = rf(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todos.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodo provides a mock function with given fields: id
func (_m *Query) GetTodo(id uint) (todos.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 todos.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (todos.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) todos.Todo); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(todos.Todo)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTodo provides a mock function with given fields: updateTodo
func (_m *Query) UpdateTodo(updateTodo todos.Todo) error {
	ret := _m.Called(updateTodo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(todos.Todo) error); ok {
		r0 = rf(updateTodo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuery creates a new instance of Query. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *Query {
	mock := &Query{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
