// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	todos "first-task-alterra/internal/features/todos"

	mock "github.com/stretchr/testify/mock"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// AddTodo provides a mock function with given fields: newActivity, userId
func (_m *Services) AddTodo(newActivity string, userId uint) error {
	ret := _m.Called(newActivity, userId)

	if len(ret) == 0 {
		panic("no return value specified for AddTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = rf(newActivity, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTodo provides a mock function with given fields: id
func (_m *Services) DeleteTodo(id uint) (todos.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 todos.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (todos.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) todos.Todo); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(todos.Todo)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTodo provides a mock function with given fields: id
func (_m *Services) FindTodo(id uint) ([]todos.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindTodo")
	}

	var r0 []todos.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]todos.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) []todos.Todo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todos.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTodo provides a mock function with given fields: id, newActivity, newMark, owner
func (_m *Services) UpdateTodo(id uint, newActivity string, newMark bool, owner uint) error {
	ret := _m.Called(id, newActivity, newMark, owner)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string, bool, uint) error); ok {
		r0 = rf(id, newActivity, newMark, owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServices creates a new instance of Services. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
